pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Hello World') {
      steps {
        script {
          writeFile file: 'hello.js', text: '''
            console.log("Hello, World from Node.js!");
          '''
          sh 'node hello.js'
        }
      }
    }
  }
}
