pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
   stage('Hello Worl') {
      steps {
        sh '''
        echo "console.log('Hello, Worl!');" > hello.js
        node hello.js
        '''
      }
    }
  }
}

